drop table if exists card;
drop table if exists product;
drop table if exists receipt;

create table card
(
    id       integer generated by default as identity
        constraint pk_card
            primary key,
    number   integer,
    discount integer
);

create table product
(
    id    serial
        primary key,
    name  varchar(255),
    price double precision,
    stock integer not null
);

create table receipt
(
    id       serial
        primary key,
    quantity integer
);

INSERT INTO public.card (id, number, discount) VALUES (1, 1111, 10);
INSERT INTO public.card (id, number, discount) VALUES (4, 4444, 10);
INSERT INTO public.card (id, number, discount) VALUES (2, 2222, 20);
INSERT INTO public.card (id, number, discount) VALUES (3, 3333, 30);
INSERT INTO public.card (id, number, discount) VALUES (6, 6666, 30);
INSERT INTO public.card (id, number, discount) VALUES (5, 5555, 20);


INSERT INTO public.product (id, name, price, stock) VALUES (2, 'Asus TUF Gaming GeForce RTX 3080 Ti OC 12GB', 4356.99, 1);
INSERT INTO public.product (id, name, price, stock) VALUES (9, 'AMD Radeon RX 6600 XT', 4563.08, 1);
INSERT INTO public.product (id, name, price, stock) VALUES (4, 'MSI GeForce RTX 3060 Ti Ventus 2X8 GBOCV1LHR', 3108.4, 1);
INSERT INTO public.product (id, name, price, stock) VALUES (3, 'ASRock Radeon RX6900 XT Phantom Gaming DOC 16GB', 3598.11, 0);
INSERT INTO public.product (id, name, price, stock) VALUES (6, 'Nvidia GeForce RTX 3070', 4011.35, 0);
INSERT INTO public.product (id, name, price, stock) VALUES (8, 'Nvidia GeForce RTX 3060 Ti', 4231.88, 0);
INSERT INTO public.product (id, name, price, stock) VALUES (5, 'Gigabyte Radeon RX 6600 XT Eagle 8GB', 8392.68, 1);
INSERT INTO public.product (id, name, price, stock) VALUES (10, 'Nvidia GeForce RTX 3060 12GB', 4009.56, 1);
INSERT INTO public.product (id, name, price, stock) VALUES (7, 'AMD Radeon RX 6700 XT', 3151.7, 1);
INSERT INTO public.product (id, name, price, stock) VALUES (1, 'Palit GeForce RTX 3070 Ti Gaming Pro 8GB', 4993.17, 1);


INSERT INTO public.receipt (id, quantity) VALUES (1, 20);
INSERT INTO public.receipt (id, quantity) VALUES (2, 10);
INSERT INTO public.receipt (id, quantity) VALUES (3, 5);
INSERT INTO public.receipt (id, quantity) VALUES (4, 4);
INSERT INTO public.receipt (id, quantity) VALUES (5, 2);
INSERT INTO public.receipt (id, quantity) VALUES (6, 18);
INSERT INTO public.receipt (id, quantity) VALUES (7, 20);
INSERT INTO public.receipt (id, quantity) VALUES (8, 10);
INSERT INTO public.receipt (id, quantity) VALUES (9, 11);
INSERT INTO public.receipt (id, quantity) VALUES (10, 21);
